import { z } from 'zod';
export declare const HealthResponse: z.ZodObject<{
    status: z.ZodEnum<{
        degraded: "degraded";
        ok: "ok";
        fail: "fail";
    }>;
    service: z.ZodString;
    version: z.ZodString;
    mode: z.ZodEnum<{
        live: "live";
        simulated: "simulated";
        sandbox: "sandbox";
    }>;
    uptimeSeconds: z.ZodNumber;
    database: z.ZodObject<{
        engine: z.ZodString;
        path: z.ZodString;
        ok: z.ZodBoolean;
    }, z.core.$strip>;
    providers: z.ZodArray<z.ZodObject<{
        provider: z.ZodEnum<{
            paypal: "paypal";
            channel3: "channel3";
            elastic: "elastic";
            zapier: "zapier";
            astropods: "astropods";
            kernel: "kernel";
            bryntum: "bryntum";
            "ag-grid": "ag-grid";
            apimatic: "apimatic";
            postman: "postman";
            internal: "internal";
            "local-catalog": "local-catalog";
        }>;
        status: z.ZodEnum<{
            live: "live";
            configured: "configured";
            unavailable: "unavailable";
            degraded: "degraded";
            simulated: "simulated";
            not_applicable: "not_applicable";
        }>;
        detail: z.ZodString;
        checkedAt: z.ZodString;
        endpoint: z.ZodOptional<z.ZodString>;
        requiresCredentials: z.ZodBoolean;
    }, z.core.$strip>>;
    checks: z.ZodObject<{
        policyEngine: z.ZodBoolean;
        eventLog: z.ZodBoolean;
        paymentAdapter: z.ZodBoolean;
    }, z.core.$strip>;
    timestamp: z.ZodString;
}, z.core.$strip>;
export type HealthResponseT = z.infer<typeof HealthResponse>;
export declare const CreateIntentResponse: z.ZodObject<{
    intent: z.ZodObject<{
        id: z.ZodString;
        runId: z.ZodOptional<z.ZodString>;
        rawText: z.ZodString;
        category: z.ZodEnum<{
            laptop: "laptop";
            desktop: "desktop";
            components: "components";
            monitor: "monitor";
            accessory: "accessory";
            phone: "phone";
            tablet: "tablet";
            audio: "audio";
            other: "other";
        }>;
        constraints: z.ZodObject<{
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
            budgetMax: z.ZodOptional<z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>>;
            budgetMin: z.ZodOptional<z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>>;
            numeric: z.ZodArray<z.ZodObject<{
                field: z.ZodString;
                label: z.ZodString;
                op: z.ZodEnum<{
                    gte: "gte";
                    lte: "lte";
                    eq: "eq";
                    gt: "gt";
                    lt: "lt";
                    between: "between";
                }>;
                value: z.ZodNumber;
                valueMax: z.ZodOptional<z.ZodNumber>;
                unit: z.ZodOptional<z.ZodString>;
                source: z.ZodEnum<{
                    default: "default";
                    user: "user";
                    policy: "policy";
                    inferred: "inferred";
                }>;
                weight: z.ZodDefault<z.ZodNumber>;
                hard: z.ZodDefault<z.ZodBoolean>;
            }, z.core.$strip>>;
            keywords: z.ZodArray<z.ZodString>;
            preferences: z.ZodArray<z.ZodString>;
            blockedCategories: z.ZodArray<z.ZodEnum<{
                laptop: "laptop";
                desktop: "desktop";
                components: "components";
                monitor: "monitor";
                accessory: "accessory";
                phone: "phone";
                tablet: "tablet";
                audio: "audio";
                other: "other";
            }>>;
            excludedTerms: z.ZodArray<z.ZodString>;
            requireApproval: z.ZodBoolean;
        }, z.core.$strip>;
        budget: z.ZodOptional<z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>>;
        approvalRequired: z.ZodBoolean;
        createdAt: z.ZodString;
        status: z.ZodEnum<{
            draft: "draft";
            interpreted: "interpreted";
            discovering: "discovering";
            evaluated: "evaluated";
            decided: "decided";
            blocked: "blocked";
            failed: "failed";
        }>;
        engine: z.ZodObject<{
            name: z.ZodEnum<{
                deterministic: "deterministic";
                "llm-assisted": "llm-assisted";
                llm: "llm";
            }>;
            provider: z.ZodOptional<z.ZodString>;
            model: z.ZodOptional<z.ZodString>;
            usedLlm: z.ZodBoolean;
            latencyMs: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>;
        confidence: z.ZodNumber;
        notes: z.ZodArray<z.ZodString>;
        openQuestions: z.ZodArray<z.ZodString>;
    }, z.core.$strip>;
    run: z.ZodOptional<z.ZodObject<{
        id: z.ZodString;
        intentId: z.ZodString;
        correlationId: z.ZodString;
        stage: z.ZodEnum<{
            policy: "policy";
            intent: "intent";
            discover: "discover";
            evaluate: "evaluate";
            decide: "decide";
            prepare: "prepare";
            approve: "approve";
            pay: "pay";
            verify: "verify";
            automate: "automate";
            audit: "audit";
            done: "done";
        }>;
        status: z.ZodEnum<{
            blocked: "blocked";
            failed: "failed";
            awaiting_approval: "awaiting_approval";
            cancelled: "cancelled";
            queued: "queued";
            running: "running";
            completed: "completed";
        }>;
        engine: z.ZodObject<{
            name: z.ZodEnum<{
                deterministic: "deterministic";
                "llm-assisted": "llm-assisted";
                llm: "llm";
            }>;
            provider: z.ZodOptional<z.ZodString>;
            model: z.ZodOptional<z.ZodString>;
            usedLlm: z.ZodBoolean;
            latencyMs: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        progress: z.ZodNumber;
        progressLabel: z.ZodString;
        candidateCount: z.ZodNumber;
        shortlistedProductIds: z.ZodArray<z.ZodString>;
        planId: z.ZodNullable<z.ZodString>;
        policyId: z.ZodNullable<z.ZodString>;
        blockedReason: z.ZodNullable<z.ZodString>;
        summary: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type CreateIntentResponseT = z.infer<typeof CreateIntentResponse>;
export declare const RunResponse: z.ZodObject<{
    run: z.ZodObject<{
        id: z.ZodString;
        intentId: z.ZodString;
        correlationId: z.ZodString;
        stage: z.ZodEnum<{
            policy: "policy";
            intent: "intent";
            discover: "discover";
            evaluate: "evaluate";
            decide: "decide";
            prepare: "prepare";
            approve: "approve";
            pay: "pay";
            verify: "verify";
            automate: "automate";
            audit: "audit";
            done: "done";
        }>;
        status: z.ZodEnum<{
            blocked: "blocked";
            failed: "failed";
            awaiting_approval: "awaiting_approval";
            cancelled: "cancelled";
            queued: "queued";
            running: "running";
            completed: "completed";
        }>;
        engine: z.ZodObject<{
            name: z.ZodEnum<{
                deterministic: "deterministic";
                "llm-assisted": "llm-assisted";
                llm: "llm";
            }>;
            provider: z.ZodOptional<z.ZodString>;
            model: z.ZodOptional<z.ZodString>;
            usedLlm: z.ZodBoolean;
            latencyMs: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        progress: z.ZodNumber;
        progressLabel: z.ZodString;
        candidateCount: z.ZodNumber;
        shortlistedProductIds: z.ZodArray<z.ZodString>;
        planId: z.ZodNullable<z.ZodString>;
        policyId: z.ZodNullable<z.ZodString>;
        blockedReason: z.ZodNullable<z.ZodString>;
        summary: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>;
export type RunResponseT = z.infer<typeof RunResponse>;
export declare const RunDetailResponse: z.ZodObject<{
    run: z.ZodObject<{
        id: z.ZodString;
        intentId: z.ZodString;
        correlationId: z.ZodString;
        stage: z.ZodEnum<{
            policy: "policy";
            intent: "intent";
            discover: "discover";
            evaluate: "evaluate";
            decide: "decide";
            prepare: "prepare";
            approve: "approve";
            pay: "pay";
            verify: "verify";
            automate: "automate";
            audit: "audit";
            done: "done";
        }>;
        status: z.ZodEnum<{
            blocked: "blocked";
            failed: "failed";
            awaiting_approval: "awaiting_approval";
            cancelled: "cancelled";
            queued: "queued";
            running: "running";
            completed: "completed";
        }>;
        engine: z.ZodObject<{
            name: z.ZodEnum<{
                deterministic: "deterministic";
                "llm-assisted": "llm-assisted";
                llm: "llm";
            }>;
            provider: z.ZodOptional<z.ZodString>;
            model: z.ZodOptional<z.ZodString>;
            usedLlm: z.ZodBoolean;
            latencyMs: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        progress: z.ZodNumber;
        progressLabel: z.ZodString;
        candidateCount: z.ZodNumber;
        shortlistedProductIds: z.ZodArray<z.ZodString>;
        planId: z.ZodNullable<z.ZodString>;
        policyId: z.ZodNullable<z.ZodString>;
        blockedReason: z.ZodNullable<z.ZodString>;
        summary: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
    intent: z.ZodObject<{
        id: z.ZodString;
        runId: z.ZodOptional<z.ZodString>;
        rawText: z.ZodString;
        category: z.ZodEnum<{
            laptop: "laptop";
            desktop: "desktop";
            components: "components";
            monitor: "monitor";
            accessory: "accessory";
            phone: "phone";
            tablet: "tablet";
            audio: "audio";
            other: "other";
        }>;
        constraints: z.ZodObject<{
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
            budgetMax: z.ZodOptional<z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>>;
            budgetMin: z.ZodOptional<z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>>;
            numeric: z.ZodArray<z.ZodObject<{
                field: z.ZodString;
                label: z.ZodString;
                op: z.ZodEnum<{
                    gte: "gte";
                    lte: "lte";
                    eq: "eq";
                    gt: "gt";
                    lt: "lt";
                    between: "between";
                }>;
                value: z.ZodNumber;
                valueMax: z.ZodOptional<z.ZodNumber>;
                unit: z.ZodOptional<z.ZodString>;
                source: z.ZodEnum<{
                    default: "default";
                    user: "user";
                    policy: "policy";
                    inferred: "inferred";
                }>;
                weight: z.ZodDefault<z.ZodNumber>;
                hard: z.ZodDefault<z.ZodBoolean>;
            }, z.core.$strip>>;
            keywords: z.ZodArray<z.ZodString>;
            preferences: z.ZodArray<z.ZodString>;
            blockedCategories: z.ZodArray<z.ZodEnum<{
                laptop: "laptop";
                desktop: "desktop";
                components: "components";
                monitor: "monitor";
                accessory: "accessory";
                phone: "phone";
                tablet: "tablet";
                audio: "audio";
                other: "other";
            }>>;
            excludedTerms: z.ZodArray<z.ZodString>;
            requireApproval: z.ZodBoolean;
        }, z.core.$strip>;
        budget: z.ZodOptional<z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>>;
        approvalRequired: z.ZodBoolean;
        createdAt: z.ZodString;
        status: z.ZodEnum<{
            draft: "draft";
            interpreted: "interpreted";
            discovering: "discovering";
            evaluated: "evaluated";
            decided: "decided";
            blocked: "blocked";
            failed: "failed";
        }>;
        engine: z.ZodObject<{
            name: z.ZodEnum<{
                deterministic: "deterministic";
                "llm-assisted": "llm-assisted";
                llm: "llm";
            }>;
            provider: z.ZodOptional<z.ZodString>;
            model: z.ZodOptional<z.ZodString>;
            usedLlm: z.ZodBoolean;
            latencyMs: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>;
        confidence: z.ZodNumber;
        notes: z.ZodArray<z.ZodString>;
        openQuestions: z.ZodArray<z.ZodString>;
    }, z.core.$strip>;
    products: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        provider: z.ZodString;
        externalId: z.ZodString;
        title: z.ZodString;
        brand: z.ZodOptional<z.ZodString>;
        category: z.ZodEnum<{
            laptop: "laptop";
            desktop: "desktop";
            components: "components";
            monitor: "monitor";
            accessory: "accessory";
            phone: "phone";
            tablet: "tablet";
            audio: "audio";
            other: "other";
        }>;
        price: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        listPrice: z.ZodOptional<z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>>;
        currency: z.ZodEnum<{
            USD: "USD";
            EUR: "EUR";
            GBP: "GBP";
            CAD: "CAD";
            AUD: "AUD";
            JPY: "JPY";
        }>;
        attributes: z.ZodArray<z.ZodObject<{
            key: z.ZodString;
            label: z.ZodString;
            value: z.ZodNullable<z.ZodUnion<readonly [z.ZodString, z.ZodNumber, z.ZodBoolean]>>;
            unit: z.ZodOptional<z.ZodString>;
            numericValue: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
            evidence: z.ZodObject<{
                kind: z.ZodEnum<{
                    provider_field: "provider_field";
                    provider_page: "provider_page";
                    computed: "computed";
                    user_statement: "user_statement";
                    unverified: "unverified";
                }>;
                source: z.ZodString;
                field: z.ZodOptional<z.ZodString>;
                url: z.ZodOptional<z.ZodString>;
                confidence: z.ZodNumber;
                observedAt: z.ZodString;
            }, z.core.$strip>;
        }, z.core.$strip>>;
        availability: z.ZodObject<{
            status: z.ZodEnum<{
                unknown: "unknown";
                in_stock: "in_stock";
                out_of_stock: "out_of_stock";
                preorder: "preorder";
                backorder: "backorder";
            }>;
            quantity: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
            observedAt: z.ZodString;
            evidence: z.ZodOptional<z.ZodObject<{
                kind: z.ZodEnum<{
                    provider_field: "provider_field";
                    provider_page: "provider_page";
                    computed: "computed";
                    user_statement: "user_statement";
                    unverified: "unverified";
                }>;
                source: z.ZodString;
                field: z.ZodOptional<z.ZodString>;
                url: z.ZodOptional<z.ZodString>;
                confidence: z.ZodNumber;
                observedAt: z.ZodString;
            }, z.core.$strip>>;
        }, z.core.$strip>;
        sourceUrl: z.ZodString;
        evidenceRefs: z.ZodArray<z.ZodObject<{
            kind: z.ZodEnum<{
                provider_field: "provider_field";
                provider_page: "provider_page";
                computed: "computed";
                user_statement: "user_statement";
                unverified: "unverified";
            }>;
            source: z.ZodString;
            field: z.ZodOptional<z.ZodString>;
            url: z.ZodOptional<z.ZodString>;
            confidence: z.ZodNumber;
            observedAt: z.ZodString;
        }, z.core.$strip>>;
        retrievedAt: z.ZodString;
        raw: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, z.core.$strip>>;
    evaluations: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        intentId: z.ZodString;
        productId: z.ZodString;
        constraintResults: z.ZodArray<z.ZodObject<{
            field: z.ZodString;
            label: z.ZodString;
            op: z.ZodEnum<{
                gte: "gte";
                lte: "lte";
                eq: "eq";
                gt: "gt";
                lt: "lt";
                between: "between";
            }>;
            expected: z.ZodString;
            actual: z.ZodNullable<z.ZodString>;
            satisfied: z.ZodNullable<z.ZodBoolean>;
            hard: z.ZodBoolean;
            evidence: z.ZodOptional<z.ZodObject<{
                kind: z.ZodEnum<{
                    provider_field: "provider_field";
                    provider_page: "provider_page";
                    computed: "computed";
                    user_statement: "user_statement";
                    unverified: "unverified";
                }>;
                source: z.ZodString;
                field: z.ZodOptional<z.ZodString>;
                url: z.ZodOptional<z.ZodString>;
                confidence: z.ZodNumber;
                observedAt: z.ZodString;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
        evidenceQuality: z.ZodObject<{
            score: z.ZodNumber;
            verifiedFields: z.ZodArray<z.ZodString>;
            unverifiedFields: z.ZodArray<z.ZodString>;
            gaps: z.ZodArray<z.ZodString>;
        }, z.core.$strip>;
        tradeoffs: z.ZodArray<z.ZodObject<{
            aspect: z.ZodString;
            direction: z.ZodEnum<{
                pro: "pro";
                con: "con";
            }>;
            detail: z.ZodString;
            weight: z.ZodNumber;
        }, z.core.$strip>>;
        score: z.ZodNumber;
        scoreBreakdown: z.ZodArray<z.ZodObject<{
            field: z.ZodString;
            label: z.ZodString;
            contribution: z.ZodNumber;
            weight: z.ZodNumber;
            reason: z.ZodString;
        }, z.core.$strip>>;
        disqualified: z.ZodArray<z.ZodString>;
        modelVersion: z.ZodString;
        rank: z.ZodOptional<z.ZodNumber>;
        createdAt: z.ZodString;
    }, z.core.$strip>>;
    shortlist: z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        runId: z.ZodString;
        intentId: z.ZodString;
        entries: z.ZodArray<z.ZodObject<{
            rank: z.ZodNumber;
            productId: z.ZodString;
            evaluationId: z.ZodString;
            score: z.ZodNumber;
            rationale: z.ZodString;
        }, z.core.$strip>>;
        rejected: z.ZodArray<z.ZodObject<{
            productId: z.ZodString;
            reason: z.ZodString;
            failedConstraints: z.ZodArray<z.ZodString>;
        }, z.core.$strip>>;
        explanation: z.ZodArray<z.ZodString>;
        createdAt: z.ZodString;
    }, z.core.$strip>>;
    plan: z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        runId: z.ZodString;
        intentId: z.ZodString;
        product: z.ZodObject<{
            id: z.ZodString;
            provider: z.ZodString;
            externalId: z.ZodString;
            title: z.ZodString;
            brand: z.ZodOptional<z.ZodString>;
            category: z.ZodEnum<{
                laptop: "laptop";
                desktop: "desktop";
                components: "components";
                monitor: "monitor";
                accessory: "accessory";
                phone: "phone";
                tablet: "tablet";
                audio: "audio";
                other: "other";
            }>;
            price: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            listPrice: z.ZodOptional<z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>>;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
            attributes: z.ZodArray<z.ZodObject<{
                key: z.ZodString;
                label: z.ZodString;
                value: z.ZodNullable<z.ZodUnion<readonly [z.ZodString, z.ZodNumber, z.ZodBoolean]>>;
                unit: z.ZodOptional<z.ZodString>;
                numericValue: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
                evidence: z.ZodObject<{
                    kind: z.ZodEnum<{
                        provider_field: "provider_field";
                        provider_page: "provider_page";
                        computed: "computed";
                        user_statement: "user_statement";
                        unverified: "unverified";
                    }>;
                    source: z.ZodString;
                    field: z.ZodOptional<z.ZodString>;
                    url: z.ZodOptional<z.ZodString>;
                    confidence: z.ZodNumber;
                    observedAt: z.ZodString;
                }, z.core.$strip>;
            }, z.core.$strip>>;
            availability: z.ZodObject<{
                status: z.ZodEnum<{
                    unknown: "unknown";
                    in_stock: "in_stock";
                    out_of_stock: "out_of_stock";
                    preorder: "preorder";
                    backorder: "backorder";
                }>;
                quantity: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
                observedAt: z.ZodString;
                evidence: z.ZodOptional<z.ZodObject<{
                    kind: z.ZodEnum<{
                        provider_field: "provider_field";
                        provider_page: "provider_page";
                        computed: "computed";
                        user_statement: "user_statement";
                        unverified: "unverified";
                    }>;
                    source: z.ZodString;
                    field: z.ZodOptional<z.ZodString>;
                    url: z.ZodOptional<z.ZodString>;
                    confidence: z.ZodNumber;
                    observedAt: z.ZodString;
                }, z.core.$strip>>;
            }, z.core.$strip>;
            sourceUrl: z.ZodString;
            evidenceRefs: z.ZodArray<z.ZodObject<{
                kind: z.ZodEnum<{
                    provider_field: "provider_field";
                    provider_page: "provider_page";
                    computed: "computed";
                    user_statement: "user_statement";
                    unverified: "unverified";
                }>;
                source: z.ZodString;
                field: z.ZodOptional<z.ZodString>;
                url: z.ZodOptional<z.ZodString>;
                confidence: z.ZodNumber;
                observedAt: z.ZodString;
            }, z.core.$strip>>;
            retrievedAt: z.ZodString;
            raw: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        }, z.core.$strip>;
        lineItems: z.ZodArray<z.ZodObject<{
            productId: z.ZodString;
            title: z.ZodString;
            quantity: z.ZodNumber;
            unitPrice: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            total: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            category: z.ZodEnum<{
                laptop: "laptop";
                desktop: "desktop";
                components: "components";
                monitor: "monitor";
                accessory: "accessory";
                phone: "phone";
                tablet: "tablet";
                audio: "audio";
                other: "other";
            }>;
            merchant: z.ZodString;
        }, z.core.$strip>>;
        subtotal: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        shipping: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        tax: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        total: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        currency: z.ZodString;
        policyResult: z.ZodObject<{
            policyId: z.ZodString;
            policyVersion: z.ZodNumber;
            outcome: z.ZodEnum<{
                allow: "allow";
                requires_approval: "requires_approval";
                deny: "deny";
            }>;
            approvalRequired: z.ZodBoolean;
            rules: z.ZodArray<z.ZodObject<{
                rule: z.ZodEnum<{
                    availability: "availability";
                    currency_match: "currency_match";
                    max_transaction: "max_transaction";
                    daily_limit: "daily_limit";
                    approval_threshold: "approval_threshold";
                    blocked_category: "blocked_category";
                    allowed_category: "allowed_category";
                    blocked_merchant: "blocked_merchant";
                    quote_freshness: "quote_freshness";
                    emergency_stop: "emergency_stop";
                    suspicious_amount: "suspicious_amount";
                }>;
                outcome: z.ZodEnum<{
                    warn: "warn";
                    pass: "pass";
                    block: "block";
                }>;
                message: z.ZodString;
                detail: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
            }, z.core.$strip>>;
            evaluatedAt: z.ZodString;
            inputHash: z.ZodString;
            correlationId: z.ZodString;
        }, z.core.$strip>;
        paypalOrderId: z.ZodNullable<z.ZodString>;
        approvalId: z.ZodNullable<z.ZodString>;
        status: z.ZodEnum<{
            draft: "draft";
            failed: "failed";
            policy_blocked: "policy_blocked";
            awaiting_approval: "awaiting_approval";
            approved: "approved";
            paypal_order_created: "paypal_order_created";
            payment_pending: "payment_pending";
            paid: "paid";
            verified: "verified";
            cancelled: "cancelled";
            expired: "expired";
            stale: "stale";
        }>;
        riskFlags: z.ZodArray<z.ZodObject<{
            code: z.ZodString;
            severity: z.ZodEnum<{
                info: "info";
                warn: "warn";
                block: "block";
            }>;
            message: z.ZodString;
        }, z.core.$strip>>;
        planHash: z.ZodString;
        quotedAt: z.ZodString;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        expiresAt: z.ZodString;
        correlationId: z.ZodString;
    }, z.core.$strip>>;
    approval: z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        purchasePlanId: z.ZodString;
        runId: z.ZodString;
        authorizationScope: z.ZodObject<{
            planId: z.ZodString;
            planHash: z.ZodString;
            amount: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            currency: z.ZodString;
            policyId: z.ZodString;
            policyVersion: z.ZodNumber;
            description: z.ZodString;
            correlationId: z.ZodString;
        }, z.core.$strip>;
        status: z.ZodEnum<{
            approved: "approved";
            expired: "expired";
            pending: "pending";
            denied: "denied";
            revoked: "revoked";
            consumed: "consumed";
        }>;
        actor: z.ZodString;
        requestedAt: z.ZodString;
        approvedAt: z.ZodNullable<z.ZodString>;
        deniedAt: z.ZodNullable<z.ZodString>;
        expiresAt: z.ZodString;
        note: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    payment: z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        purchasePlanId: z.ZodString;
        runId: z.ZodString;
        paypalOrderId: z.ZodString;
        transactionId: z.ZodNullable<z.ZodString>;
        status: z.ZodEnum<{
            failed: "failed";
            awaiting_approval: "awaiting_approval";
            approved: "approved";
            cancelled: "cancelled";
            created: "created";
            captured: "captured";
            refunded: "refunded";
        }>;
        amount: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        currency: z.ZodString;
        capturedAt: z.ZodNullable<z.ZodString>;
        verificationState: z.ZodEnum<{
            unverified: "unverified";
            failed: "failed";
            verified: "verified";
        }>;
        provider: z.ZodEnum<{
            paypal: "paypal";
            simulated: "simulated";
        }>;
        mode: z.ZodEnum<{
            live: "live";
            simulated: "simulated";
            sandbox: "sandbox";
        }>;
        attempts: z.ZodNumber;
        lastError: z.ZodNullable<z.ZodString>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        raw: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, z.core.$strip>>;
    automations: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        triggerEventId: z.ZodString;
        runId: z.ZodNullable<z.ZodString>;
        purchasePlanId: z.ZodNullable<z.ZodString>;
        zapierHook: z.ZodString;
        status: z.ZodEnum<{
            failed: "failed";
            sent: "sent";
            unconfigured: "unconfigured";
            pending_retry: "pending_retry";
        }>;
        responseSummary: z.ZodString;
        executedAt: z.ZodString;
        attempt: z.ZodNumber;
    }, z.core.$strip>>;
    events: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        correlationId: z.ZodString;
        runId: z.ZodNullable<z.ZodString>;
        type: z.ZodEnum<{
            "run.created": "run.created";
            "run.stage.changed": "run.stage.changed";
            "run.failed": "run.failed";
            "run.cancelled": "run.cancelled";
            "intent.created": "intent.created";
            "intent.updated": "intent.updated";
            "catalog.search.started": "catalog.search.started";
            "catalog.search.completed": "catalog.search.completed";
            "product.retrieved": "product.retrieved";
            "product.evaluated": "product.evaluated";
            "shortlist.created": "shortlist.created";
            "evidence.gap.detected": "evidence.gap.detected";
            "policy.checked": "policy.checked";
            "policy.updated": "policy.updated";
            "plan.created": "plan.created";
            "plan.invalidated": "plan.invalidated";
            "approval.requested": "approval.requested";
            "approval.granted": "approval.granted";
            "approval.denied": "approval.denied";
            "approval.expired": "approval.expired";
            "paypal.order.created": "paypal.order.created";
            "paypal.approval.completed": "paypal.approval.completed";
            "payment.captured": "payment.captured";
            "payment.failed": "payment.failed";
            "order.verified": "order.verified";
            "automation.triggered": "automation.triggered";
            "automation.failed": "automation.failed";
            "action.failed": "action.failed";
            "tool.called": "tool.called";
            "system.health": "system.health";
        }>;
        actor: z.ZodString;
        source: z.ZodString;
        payload: z.ZodRecord<z.ZodString, z.ZodUnknown>;
        timestamp: z.ZodString;
        severity: z.ZodEnum<{
            error: "error";
            info: "info";
            warn: "warn";
        }>;
        sequence: z.ZodNumber;
    }, z.core.$strip>>;
    toolCalls: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        runId: z.ZodString;
        correlationId: z.ZodString;
        tool: z.ZodEnum<{
            parse_intent: "parse_intent";
            validate_constraints: "validate_constraints";
            catalog_search: "catalog_search";
            product_details: "product_details";
            compare_products: "compare_products";
            evidence_lookup: "evidence_lookup";
            score_candidate: "score_candidate";
            explain_tradeoffs: "explain_tradeoffs";
            policy_check: "policy_check";
            create_paypal_order: "create_paypal_order";
            request_approval: "request_approval";
            capture_payment: "capture_payment";
            get_paypal_order: "get_paypal_order";
            verify_order: "verify_order";
            trigger_automation: "trigger_automation";
            search_events: "search_events";
        }>;
        arguments: z.ZodRecord<z.ZodString, z.ZodUnknown>;
        status: z.ZodEnum<{
            error: "error";
            denied: "denied";
            ok: "ok";
        }>;
        startedAt: z.ZodString;
        durationMs: z.ZodNumber;
        resultSummary: z.ZodOptional<z.ZodString>;
        error: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type RunDetailResponseT = z.infer<typeof RunDetailResponse>;
export declare const DiscoveryResponse: z.ZodObject<{
    runId: z.ZodString;
    provider: z.ZodString;
    degraded: z.ZodBoolean;
    degradedReason: z.ZodOptional<z.ZodString>;
    tookMs: z.ZodNumber;
    products: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        provider: z.ZodString;
        externalId: z.ZodString;
        title: z.ZodString;
        brand: z.ZodOptional<z.ZodString>;
        category: z.ZodEnum<{
            laptop: "laptop";
            desktop: "desktop";
            components: "components";
            monitor: "monitor";
            accessory: "accessory";
            phone: "phone";
            tablet: "tablet";
            audio: "audio";
            other: "other";
        }>;
        price: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        listPrice: z.ZodOptional<z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>>;
        currency: z.ZodEnum<{
            USD: "USD";
            EUR: "EUR";
            GBP: "GBP";
            CAD: "CAD";
            AUD: "AUD";
            JPY: "JPY";
        }>;
        attributes: z.ZodArray<z.ZodObject<{
            key: z.ZodString;
            label: z.ZodString;
            value: z.ZodNullable<z.ZodUnion<readonly [z.ZodString, z.ZodNumber, z.ZodBoolean]>>;
            unit: z.ZodOptional<z.ZodString>;
            numericValue: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
            evidence: z.ZodObject<{
                kind: z.ZodEnum<{
                    provider_field: "provider_field";
                    provider_page: "provider_page";
                    computed: "computed";
                    user_statement: "user_statement";
                    unverified: "unverified";
                }>;
                source: z.ZodString;
                field: z.ZodOptional<z.ZodString>;
                url: z.ZodOptional<z.ZodString>;
                confidence: z.ZodNumber;
                observedAt: z.ZodString;
            }, z.core.$strip>;
        }, z.core.$strip>>;
        availability: z.ZodObject<{
            status: z.ZodEnum<{
                unknown: "unknown";
                in_stock: "in_stock";
                out_of_stock: "out_of_stock";
                preorder: "preorder";
                backorder: "backorder";
            }>;
            quantity: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
            observedAt: z.ZodString;
            evidence: z.ZodOptional<z.ZodObject<{
                kind: z.ZodEnum<{
                    provider_field: "provider_field";
                    provider_page: "provider_page";
                    computed: "computed";
                    user_statement: "user_statement";
                    unverified: "unverified";
                }>;
                source: z.ZodString;
                field: z.ZodOptional<z.ZodString>;
                url: z.ZodOptional<z.ZodString>;
                confidence: z.ZodNumber;
                observedAt: z.ZodString;
            }, z.core.$strip>>;
        }, z.core.$strip>;
        sourceUrl: z.ZodString;
        evidenceRefs: z.ZodArray<z.ZodObject<{
            kind: z.ZodEnum<{
                provider_field: "provider_field";
                provider_page: "provider_page";
                computed: "computed";
                user_statement: "user_statement";
                unverified: "unverified";
            }>;
            source: z.ZodString;
            field: z.ZodOptional<z.ZodString>;
            url: z.ZodOptional<z.ZodString>;
            confidence: z.ZodNumber;
            observedAt: z.ZodString;
        }, z.core.$strip>>;
        retrievedAt: z.ZodString;
        raw: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type DiscoveryResponseT = z.infer<typeof DiscoveryResponse>;
export declare const PolicyCheckResponse: z.ZodObject<{
    decision: z.ZodObject<{
        policyId: z.ZodString;
        policyVersion: z.ZodNumber;
        outcome: z.ZodEnum<{
            allow: "allow";
            requires_approval: "requires_approval";
            deny: "deny";
        }>;
        approvalRequired: z.ZodBoolean;
        rules: z.ZodArray<z.ZodObject<{
            rule: z.ZodEnum<{
                availability: "availability";
                currency_match: "currency_match";
                max_transaction: "max_transaction";
                daily_limit: "daily_limit";
                approval_threshold: "approval_threshold";
                blocked_category: "blocked_category";
                allowed_category: "allowed_category";
                blocked_merchant: "blocked_merchant";
                quote_freshness: "quote_freshness";
                emergency_stop: "emergency_stop";
                suspicious_amount: "suspicious_amount";
            }>;
            outcome: z.ZodEnum<{
                warn: "warn";
                pass: "pass";
                block: "block";
            }>;
            message: z.ZodString;
            detail: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        }, z.core.$strip>>;
        evaluatedAt: z.ZodString;
        inputHash: z.ZodString;
        correlationId: z.ZodString;
    }, z.core.$strip>;
    policy: z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        currency: z.ZodEnum<{
            USD: "USD";
            EUR: "EUR";
            GBP: "GBP";
            CAD: "CAD";
            AUD: "AUD";
            JPY: "JPY";
        }>;
        maxTransaction: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        dailyLimit: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        approvalThreshold: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        requireApproval: z.ZodBoolean;
        blockedCategories: z.ZodArray<z.ZodEnum<{
            laptop: "laptop";
            desktop: "desktop";
            components: "components";
            monitor: "monitor";
            accessory: "accessory";
            phone: "phone";
            tablet: "tablet";
            audio: "audio";
            other: "other";
        }>>;
        allowedCategories: z.ZodNullable<z.ZodArray<z.ZodEnum<{
            laptop: "laptop";
            desktop: "desktop";
            components: "components";
            monitor: "monitor";
            accessory: "accessory";
            phone: "phone";
            tablet: "tablet";
            audio: "audio";
            other: "other";
        }>>>;
        blockedMerchants: z.ZodArray<z.ZodString>;
        maxQuoteAgeMinutes: z.ZodNumber;
        emergencyStop: z.ZodBoolean;
        version: z.ZodNumber;
        updatedAt: z.ZodString;
    }, z.core.$strip>;
}, z.core.$strip>;
export type PolicyCheckResponseT = z.infer<typeof PolicyCheckResponse>;
export declare const PreparePurchaseResponse: z.ZodObject<{
    plan: z.ZodObject<{
        id: z.ZodString;
        runId: z.ZodString;
        intentId: z.ZodString;
        product: z.ZodObject<{
            id: z.ZodString;
            provider: z.ZodString;
            externalId: z.ZodString;
            title: z.ZodString;
            brand: z.ZodOptional<z.ZodString>;
            category: z.ZodEnum<{
                laptop: "laptop";
                desktop: "desktop";
                components: "components";
                monitor: "monitor";
                accessory: "accessory";
                phone: "phone";
                tablet: "tablet";
                audio: "audio";
                other: "other";
            }>;
            price: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            listPrice: z.ZodOptional<z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>>;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
            attributes: z.ZodArray<z.ZodObject<{
                key: z.ZodString;
                label: z.ZodString;
                value: z.ZodNullable<z.ZodUnion<readonly [z.ZodString, z.ZodNumber, z.ZodBoolean]>>;
                unit: z.ZodOptional<z.ZodString>;
                numericValue: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
                evidence: z.ZodObject<{
                    kind: z.ZodEnum<{
                        provider_field: "provider_field";
                        provider_page: "provider_page";
                        computed: "computed";
                        user_statement: "user_statement";
                        unverified: "unverified";
                    }>;
                    source: z.ZodString;
                    field: z.ZodOptional<z.ZodString>;
                    url: z.ZodOptional<z.ZodString>;
                    confidence: z.ZodNumber;
                    observedAt: z.ZodString;
                }, z.core.$strip>;
            }, z.core.$strip>>;
            availability: z.ZodObject<{
                status: z.ZodEnum<{
                    unknown: "unknown";
                    in_stock: "in_stock";
                    out_of_stock: "out_of_stock";
                    preorder: "preorder";
                    backorder: "backorder";
                }>;
                quantity: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
                observedAt: z.ZodString;
                evidence: z.ZodOptional<z.ZodObject<{
                    kind: z.ZodEnum<{
                        provider_field: "provider_field";
                        provider_page: "provider_page";
                        computed: "computed";
                        user_statement: "user_statement";
                        unverified: "unverified";
                    }>;
                    source: z.ZodString;
                    field: z.ZodOptional<z.ZodString>;
                    url: z.ZodOptional<z.ZodString>;
                    confidence: z.ZodNumber;
                    observedAt: z.ZodString;
                }, z.core.$strip>>;
            }, z.core.$strip>;
            sourceUrl: z.ZodString;
            evidenceRefs: z.ZodArray<z.ZodObject<{
                kind: z.ZodEnum<{
                    provider_field: "provider_field";
                    provider_page: "provider_page";
                    computed: "computed";
                    user_statement: "user_statement";
                    unverified: "unverified";
                }>;
                source: z.ZodString;
                field: z.ZodOptional<z.ZodString>;
                url: z.ZodOptional<z.ZodString>;
                confidence: z.ZodNumber;
                observedAt: z.ZodString;
            }, z.core.$strip>>;
            retrievedAt: z.ZodString;
            raw: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        }, z.core.$strip>;
        lineItems: z.ZodArray<z.ZodObject<{
            productId: z.ZodString;
            title: z.ZodString;
            quantity: z.ZodNumber;
            unitPrice: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            total: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            category: z.ZodEnum<{
                laptop: "laptop";
                desktop: "desktop";
                components: "components";
                monitor: "monitor";
                accessory: "accessory";
                phone: "phone";
                tablet: "tablet";
                audio: "audio";
                other: "other";
            }>;
            merchant: z.ZodString;
        }, z.core.$strip>>;
        subtotal: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        shipping: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        tax: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        total: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        currency: z.ZodString;
        policyResult: z.ZodObject<{
            policyId: z.ZodString;
            policyVersion: z.ZodNumber;
            outcome: z.ZodEnum<{
                allow: "allow";
                requires_approval: "requires_approval";
                deny: "deny";
            }>;
            approvalRequired: z.ZodBoolean;
            rules: z.ZodArray<z.ZodObject<{
                rule: z.ZodEnum<{
                    availability: "availability";
                    currency_match: "currency_match";
                    max_transaction: "max_transaction";
                    daily_limit: "daily_limit";
                    approval_threshold: "approval_threshold";
                    blocked_category: "blocked_category";
                    allowed_category: "allowed_category";
                    blocked_merchant: "blocked_merchant";
                    quote_freshness: "quote_freshness";
                    emergency_stop: "emergency_stop";
                    suspicious_amount: "suspicious_amount";
                }>;
                outcome: z.ZodEnum<{
                    warn: "warn";
                    pass: "pass";
                    block: "block";
                }>;
                message: z.ZodString;
                detail: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
            }, z.core.$strip>>;
            evaluatedAt: z.ZodString;
            inputHash: z.ZodString;
            correlationId: z.ZodString;
        }, z.core.$strip>;
        paypalOrderId: z.ZodNullable<z.ZodString>;
        approvalId: z.ZodNullable<z.ZodString>;
        status: z.ZodEnum<{
            draft: "draft";
            failed: "failed";
            policy_blocked: "policy_blocked";
            awaiting_approval: "awaiting_approval";
            approved: "approved";
            paypal_order_created: "paypal_order_created";
            payment_pending: "payment_pending";
            paid: "paid";
            verified: "verified";
            cancelled: "cancelled";
            expired: "expired";
            stale: "stale";
        }>;
        riskFlags: z.ZodArray<z.ZodObject<{
            code: z.ZodString;
            severity: z.ZodEnum<{
                info: "info";
                warn: "warn";
                block: "block";
            }>;
            message: z.ZodString;
        }, z.core.$strip>>;
        planHash: z.ZodString;
        quotedAt: z.ZodString;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        expiresAt: z.ZodString;
        correlationId: z.ZodString;
    }, z.core.$strip>;
    approval: z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        purchasePlanId: z.ZodString;
        runId: z.ZodString;
        authorizationScope: z.ZodObject<{
            planId: z.ZodString;
            planHash: z.ZodString;
            amount: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            currency: z.ZodString;
            policyId: z.ZodString;
            policyVersion: z.ZodNumber;
            description: z.ZodString;
            correlationId: z.ZodString;
        }, z.core.$strip>;
        status: z.ZodEnum<{
            approved: "approved";
            expired: "expired";
            pending: "pending";
            denied: "denied";
            revoked: "revoked";
            consumed: "consumed";
        }>;
        actor: z.ZodString;
        requestedAt: z.ZodString;
        approvedAt: z.ZodNullable<z.ZodString>;
        deniedAt: z.ZodNullable<z.ZodString>;
        expiresAt: z.ZodString;
        note: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    payment: z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        purchasePlanId: z.ZodString;
        runId: z.ZodString;
        paypalOrderId: z.ZodString;
        transactionId: z.ZodNullable<z.ZodString>;
        status: z.ZodEnum<{
            failed: "failed";
            awaiting_approval: "awaiting_approval";
            approved: "approved";
            cancelled: "cancelled";
            created: "created";
            captured: "captured";
            refunded: "refunded";
        }>;
        amount: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        currency: z.ZodString;
        capturedAt: z.ZodNullable<z.ZodString>;
        verificationState: z.ZodEnum<{
            unverified: "unverified";
            failed: "failed";
            verified: "verified";
        }>;
        provider: z.ZodEnum<{
            paypal: "paypal";
            simulated: "simulated";
        }>;
        mode: z.ZodEnum<{
            live: "live";
            simulated: "simulated";
            sandbox: "sandbox";
        }>;
        attempts: z.ZodNumber;
        lastError: z.ZodNullable<z.ZodString>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        raw: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, z.core.$strip>>;
    approvalUrl: z.ZodNullable<z.ZodString>;
    blocked: z.ZodBoolean;
}, z.core.$strip>;
export type PreparePurchaseResponseT = z.infer<typeof PreparePurchaseResponse>;
export declare const ApprovePurchaseResponse: z.ZodObject<{
    approval: z.ZodObject<{
        id: z.ZodString;
        purchasePlanId: z.ZodString;
        runId: z.ZodString;
        authorizationScope: z.ZodObject<{
            planId: z.ZodString;
            planHash: z.ZodString;
            amount: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            currency: z.ZodString;
            policyId: z.ZodString;
            policyVersion: z.ZodNumber;
            description: z.ZodString;
            correlationId: z.ZodString;
        }, z.core.$strip>;
        status: z.ZodEnum<{
            approved: "approved";
            expired: "expired";
            pending: "pending";
            denied: "denied";
            revoked: "revoked";
            consumed: "consumed";
        }>;
        actor: z.ZodString;
        requestedAt: z.ZodString;
        approvedAt: z.ZodNullable<z.ZodString>;
        deniedAt: z.ZodNullable<z.ZodString>;
        expiresAt: z.ZodString;
        note: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    plan: z.ZodObject<{
        id: z.ZodString;
        runId: z.ZodString;
        intentId: z.ZodString;
        product: z.ZodObject<{
            id: z.ZodString;
            provider: z.ZodString;
            externalId: z.ZodString;
            title: z.ZodString;
            brand: z.ZodOptional<z.ZodString>;
            category: z.ZodEnum<{
                laptop: "laptop";
                desktop: "desktop";
                components: "components";
                monitor: "monitor";
                accessory: "accessory";
                phone: "phone";
                tablet: "tablet";
                audio: "audio";
                other: "other";
            }>;
            price: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            listPrice: z.ZodOptional<z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>>;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
            attributes: z.ZodArray<z.ZodObject<{
                key: z.ZodString;
                label: z.ZodString;
                value: z.ZodNullable<z.ZodUnion<readonly [z.ZodString, z.ZodNumber, z.ZodBoolean]>>;
                unit: z.ZodOptional<z.ZodString>;
                numericValue: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
                evidence: z.ZodObject<{
                    kind: z.ZodEnum<{
                        provider_field: "provider_field";
                        provider_page: "provider_page";
                        computed: "computed";
                        user_statement: "user_statement";
                        unverified: "unverified";
                    }>;
                    source: z.ZodString;
                    field: z.ZodOptional<z.ZodString>;
                    url: z.ZodOptional<z.ZodString>;
                    confidence: z.ZodNumber;
                    observedAt: z.ZodString;
                }, z.core.$strip>;
            }, z.core.$strip>>;
            availability: z.ZodObject<{
                status: z.ZodEnum<{
                    unknown: "unknown";
                    in_stock: "in_stock";
                    out_of_stock: "out_of_stock";
                    preorder: "preorder";
                    backorder: "backorder";
                }>;
                quantity: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
                observedAt: z.ZodString;
                evidence: z.ZodOptional<z.ZodObject<{
                    kind: z.ZodEnum<{
                        provider_field: "provider_field";
                        provider_page: "provider_page";
                        computed: "computed";
                        user_statement: "user_statement";
                        unverified: "unverified";
                    }>;
                    source: z.ZodString;
                    field: z.ZodOptional<z.ZodString>;
                    url: z.ZodOptional<z.ZodString>;
                    confidence: z.ZodNumber;
                    observedAt: z.ZodString;
                }, z.core.$strip>>;
            }, z.core.$strip>;
            sourceUrl: z.ZodString;
            evidenceRefs: z.ZodArray<z.ZodObject<{
                kind: z.ZodEnum<{
                    provider_field: "provider_field";
                    provider_page: "provider_page";
                    computed: "computed";
                    user_statement: "user_statement";
                    unverified: "unverified";
                }>;
                source: z.ZodString;
                field: z.ZodOptional<z.ZodString>;
                url: z.ZodOptional<z.ZodString>;
                confidence: z.ZodNumber;
                observedAt: z.ZodString;
            }, z.core.$strip>>;
            retrievedAt: z.ZodString;
            raw: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        }, z.core.$strip>;
        lineItems: z.ZodArray<z.ZodObject<{
            productId: z.ZodString;
            title: z.ZodString;
            quantity: z.ZodNumber;
            unitPrice: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            total: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            category: z.ZodEnum<{
                laptop: "laptop";
                desktop: "desktop";
                components: "components";
                monitor: "monitor";
                accessory: "accessory";
                phone: "phone";
                tablet: "tablet";
                audio: "audio";
                other: "other";
            }>;
            merchant: z.ZodString;
        }, z.core.$strip>>;
        subtotal: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        shipping: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        tax: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        total: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        currency: z.ZodString;
        policyResult: z.ZodObject<{
            policyId: z.ZodString;
            policyVersion: z.ZodNumber;
            outcome: z.ZodEnum<{
                allow: "allow";
                requires_approval: "requires_approval";
                deny: "deny";
            }>;
            approvalRequired: z.ZodBoolean;
            rules: z.ZodArray<z.ZodObject<{
                rule: z.ZodEnum<{
                    availability: "availability";
                    currency_match: "currency_match";
                    max_transaction: "max_transaction";
                    daily_limit: "daily_limit";
                    approval_threshold: "approval_threshold";
                    blocked_category: "blocked_category";
                    allowed_category: "allowed_category";
                    blocked_merchant: "blocked_merchant";
                    quote_freshness: "quote_freshness";
                    emergency_stop: "emergency_stop";
                    suspicious_amount: "suspicious_amount";
                }>;
                outcome: z.ZodEnum<{
                    warn: "warn";
                    pass: "pass";
                    block: "block";
                }>;
                message: z.ZodString;
                detail: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
            }, z.core.$strip>>;
            evaluatedAt: z.ZodString;
            inputHash: z.ZodString;
            correlationId: z.ZodString;
        }, z.core.$strip>;
        paypalOrderId: z.ZodNullable<z.ZodString>;
        approvalId: z.ZodNullable<z.ZodString>;
        status: z.ZodEnum<{
            draft: "draft";
            failed: "failed";
            policy_blocked: "policy_blocked";
            awaiting_approval: "awaiting_approval";
            approved: "approved";
            paypal_order_created: "paypal_order_created";
            payment_pending: "payment_pending";
            paid: "paid";
            verified: "verified";
            cancelled: "cancelled";
            expired: "expired";
            stale: "stale";
        }>;
        riskFlags: z.ZodArray<z.ZodObject<{
            code: z.ZodString;
            severity: z.ZodEnum<{
                info: "info";
                warn: "warn";
                block: "block";
            }>;
            message: z.ZodString;
        }, z.core.$strip>>;
        planHash: z.ZodString;
        quotedAt: z.ZodString;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        expiresAt: z.ZodString;
        correlationId: z.ZodString;
    }, z.core.$strip>;
}, z.core.$strip>;
export type ApprovePurchaseResponseT = z.infer<typeof ApprovePurchaseResponse>;
export declare const CapturePurchaseResponse: z.ZodObject<{
    payment: z.ZodObject<{
        id: z.ZodString;
        purchasePlanId: z.ZodString;
        runId: z.ZodString;
        paypalOrderId: z.ZodString;
        transactionId: z.ZodNullable<z.ZodString>;
        status: z.ZodEnum<{
            failed: "failed";
            awaiting_approval: "awaiting_approval";
            approved: "approved";
            cancelled: "cancelled";
            created: "created";
            captured: "captured";
            refunded: "refunded";
        }>;
        amount: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        currency: z.ZodString;
        capturedAt: z.ZodNullable<z.ZodString>;
        verificationState: z.ZodEnum<{
            unverified: "unverified";
            failed: "failed";
            verified: "verified";
        }>;
        provider: z.ZodEnum<{
            paypal: "paypal";
            simulated: "simulated";
        }>;
        mode: z.ZodEnum<{
            live: "live";
            simulated: "simulated";
            sandbox: "sandbox";
        }>;
        attempts: z.ZodNumber;
        lastError: z.ZodNullable<z.ZodString>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        raw: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, z.core.$strip>;
    plan: z.ZodObject<{
        id: z.ZodString;
        runId: z.ZodString;
        intentId: z.ZodString;
        product: z.ZodObject<{
            id: z.ZodString;
            provider: z.ZodString;
            externalId: z.ZodString;
            title: z.ZodString;
            brand: z.ZodOptional<z.ZodString>;
            category: z.ZodEnum<{
                laptop: "laptop";
                desktop: "desktop";
                components: "components";
                monitor: "monitor";
                accessory: "accessory";
                phone: "phone";
                tablet: "tablet";
                audio: "audio";
                other: "other";
            }>;
            price: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            listPrice: z.ZodOptional<z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>>;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
            attributes: z.ZodArray<z.ZodObject<{
                key: z.ZodString;
                label: z.ZodString;
                value: z.ZodNullable<z.ZodUnion<readonly [z.ZodString, z.ZodNumber, z.ZodBoolean]>>;
                unit: z.ZodOptional<z.ZodString>;
                numericValue: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
                evidence: z.ZodObject<{
                    kind: z.ZodEnum<{
                        provider_field: "provider_field";
                        provider_page: "provider_page";
                        computed: "computed";
                        user_statement: "user_statement";
                        unverified: "unverified";
                    }>;
                    source: z.ZodString;
                    field: z.ZodOptional<z.ZodString>;
                    url: z.ZodOptional<z.ZodString>;
                    confidence: z.ZodNumber;
                    observedAt: z.ZodString;
                }, z.core.$strip>;
            }, z.core.$strip>>;
            availability: z.ZodObject<{
                status: z.ZodEnum<{
                    unknown: "unknown";
                    in_stock: "in_stock";
                    out_of_stock: "out_of_stock";
                    preorder: "preorder";
                    backorder: "backorder";
                }>;
                quantity: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
                observedAt: z.ZodString;
                evidence: z.ZodOptional<z.ZodObject<{
                    kind: z.ZodEnum<{
                        provider_field: "provider_field";
                        provider_page: "provider_page";
                        computed: "computed";
                        user_statement: "user_statement";
                        unverified: "unverified";
                    }>;
                    source: z.ZodString;
                    field: z.ZodOptional<z.ZodString>;
                    url: z.ZodOptional<z.ZodString>;
                    confidence: z.ZodNumber;
                    observedAt: z.ZodString;
                }, z.core.$strip>>;
            }, z.core.$strip>;
            sourceUrl: z.ZodString;
            evidenceRefs: z.ZodArray<z.ZodObject<{
                kind: z.ZodEnum<{
                    provider_field: "provider_field";
                    provider_page: "provider_page";
                    computed: "computed";
                    user_statement: "user_statement";
                    unverified: "unverified";
                }>;
                source: z.ZodString;
                field: z.ZodOptional<z.ZodString>;
                url: z.ZodOptional<z.ZodString>;
                confidence: z.ZodNumber;
                observedAt: z.ZodString;
            }, z.core.$strip>>;
            retrievedAt: z.ZodString;
            raw: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        }, z.core.$strip>;
        lineItems: z.ZodArray<z.ZodObject<{
            productId: z.ZodString;
            title: z.ZodString;
            quantity: z.ZodNumber;
            unitPrice: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            total: z.ZodObject<{
                amount: z.ZodNumber;
                currency: z.ZodEnum<{
                    USD: "USD";
                    EUR: "EUR";
                    GBP: "GBP";
                    CAD: "CAD";
                    AUD: "AUD";
                    JPY: "JPY";
                }>;
            }, z.core.$strip>;
            category: z.ZodEnum<{
                laptop: "laptop";
                desktop: "desktop";
                components: "components";
                monitor: "monitor";
                accessory: "accessory";
                phone: "phone";
                tablet: "tablet";
                audio: "audio";
                other: "other";
            }>;
            merchant: z.ZodString;
        }, z.core.$strip>>;
        subtotal: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        shipping: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        tax: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        total: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        currency: z.ZodString;
        policyResult: z.ZodObject<{
            policyId: z.ZodString;
            policyVersion: z.ZodNumber;
            outcome: z.ZodEnum<{
                allow: "allow";
                requires_approval: "requires_approval";
                deny: "deny";
            }>;
            approvalRequired: z.ZodBoolean;
            rules: z.ZodArray<z.ZodObject<{
                rule: z.ZodEnum<{
                    availability: "availability";
                    currency_match: "currency_match";
                    max_transaction: "max_transaction";
                    daily_limit: "daily_limit";
                    approval_threshold: "approval_threshold";
                    blocked_category: "blocked_category";
                    allowed_category: "allowed_category";
                    blocked_merchant: "blocked_merchant";
                    quote_freshness: "quote_freshness";
                    emergency_stop: "emergency_stop";
                    suspicious_amount: "suspicious_amount";
                }>;
                outcome: z.ZodEnum<{
                    warn: "warn";
                    pass: "pass";
                    block: "block";
                }>;
                message: z.ZodString;
                detail: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
            }, z.core.$strip>>;
            evaluatedAt: z.ZodString;
            inputHash: z.ZodString;
            correlationId: z.ZodString;
        }, z.core.$strip>;
        paypalOrderId: z.ZodNullable<z.ZodString>;
        approvalId: z.ZodNullable<z.ZodString>;
        status: z.ZodEnum<{
            draft: "draft";
            failed: "failed";
            policy_blocked: "policy_blocked";
            awaiting_approval: "awaiting_approval";
            approved: "approved";
            paypal_order_created: "paypal_order_created";
            payment_pending: "payment_pending";
            paid: "paid";
            verified: "verified";
            cancelled: "cancelled";
            expired: "expired";
            stale: "stale";
        }>;
        riskFlags: z.ZodArray<z.ZodObject<{
            code: z.ZodString;
            severity: z.ZodEnum<{
                info: "info";
                warn: "warn";
                block: "block";
            }>;
            message: z.ZodString;
        }, z.core.$strip>>;
        planHash: z.ZodString;
        quotedAt: z.ZodString;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        expiresAt: z.ZodString;
        correlationId: z.ZodString;
    }, z.core.$strip>;
    automation: z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        triggerEventId: z.ZodString;
        runId: z.ZodNullable<z.ZodString>;
        purchasePlanId: z.ZodNullable<z.ZodString>;
        zapierHook: z.ZodString;
        status: z.ZodEnum<{
            failed: "failed";
            sent: "sent";
            unconfigured: "unconfigured";
            pending_retry: "pending_retry";
        }>;
        responseSummary: z.ZodString;
        executedAt: z.ZodString;
        attempt: z.ZodNumber;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type CapturePurchaseResponseT = z.infer<typeof CapturePurchaseResponse>;
export declare const AutomationTestResponse: z.ZodObject<{
    status: z.ZodEnum<{
        failed: "failed";
        sent: "sent";
        unconfigured: "unconfigured";
    }>;
    hook: z.ZodString;
    responseSummary: z.ZodString;
    durationMs: z.ZodNumber;
    run: z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        triggerEventId: z.ZodString;
        runId: z.ZodNullable<z.ZodString>;
        purchasePlanId: z.ZodNullable<z.ZodString>;
        zapierHook: z.ZodString;
        status: z.ZodEnum<{
            failed: "failed";
            sent: "sent";
            unconfigured: "unconfigured";
            pending_retry: "pending_retry";
        }>;
        responseSummary: z.ZodString;
        executedAt: z.ZodString;
        attempt: z.ZodNumber;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type AutomationTestResponseT = z.infer<typeof AutomationTestResponse>;
export declare const IdempotentReplay: z.ZodObject<{
    idempotentReplay: z.ZodBoolean;
    correlationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const ListPoliciesResponse: z.ZodObject<{
    policies: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        currency: z.ZodEnum<{
            USD: "USD";
            EUR: "EUR";
            GBP: "GBP";
            CAD: "CAD";
            AUD: "AUD";
            JPY: "JPY";
        }>;
        maxTransaction: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        dailyLimit: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        approvalThreshold: z.ZodObject<{
            amount: z.ZodNumber;
            currency: z.ZodEnum<{
                USD: "USD";
                EUR: "EUR";
                GBP: "GBP";
                CAD: "CAD";
                AUD: "AUD";
                JPY: "JPY";
            }>;
        }, z.core.$strip>;
        requireApproval: z.ZodBoolean;
        blockedCategories: z.ZodArray<z.ZodEnum<{
            laptop: "laptop";
            desktop: "desktop";
            components: "components";
            monitor: "monitor";
            accessory: "accessory";
            phone: "phone";
            tablet: "tablet";
            audio: "audio";
            other: "other";
        }>>;
        allowedCategories: z.ZodNullable<z.ZodArray<z.ZodEnum<{
            laptop: "laptop";
            desktop: "desktop";
            components: "components";
            monitor: "monitor";
            accessory: "accessory";
            phone: "phone";
            tablet: "tablet";
            audio: "audio";
            other: "other";
        }>>>;
        blockedMerchants: z.ZodArray<z.ZodString>;
        maxQuoteAgeMinutes: z.ZodNumber;
        emergencyStop: z.ZodBoolean;
        version: z.ZodNumber;
        updatedAt: z.ZodString;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type ListPoliciesResponseT = z.infer<typeof ListPoliciesResponse>;
export declare const ListRunsResponse: z.ZodObject<{
    runs: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        intentId: z.ZodString;
        correlationId: z.ZodString;
        stage: z.ZodEnum<{
            policy: "policy";
            intent: "intent";
            discover: "discover";
            evaluate: "evaluate";
            decide: "decide";
            prepare: "prepare";
            approve: "approve";
            pay: "pay";
            verify: "verify";
            automate: "automate";
            audit: "audit";
            done: "done";
        }>;
        status: z.ZodEnum<{
            blocked: "blocked";
            failed: "failed";
            awaiting_approval: "awaiting_approval";
            cancelled: "cancelled";
            queued: "queued";
            running: "running";
            completed: "completed";
        }>;
        engine: z.ZodObject<{
            name: z.ZodEnum<{
                deterministic: "deterministic";
                "llm-assisted": "llm-assisted";
                llm: "llm";
            }>;
            provider: z.ZodOptional<z.ZodString>;
            model: z.ZodOptional<z.ZodString>;
            usedLlm: z.ZodBoolean;
            latencyMs: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        progress: z.ZodNumber;
        progressLabel: z.ZodString;
        candidateCount: z.ZodNumber;
        shortlistedProductIds: z.ZodArray<z.ZodString>;
        planId: z.ZodNullable<z.ZodString>;
        policyId: z.ZodNullable<z.ZodString>;
        blockedReason: z.ZodNullable<z.ZodString>;
        summary: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type ListRunsResponseT = z.infer<typeof ListRunsResponse>;
export declare const OkResponse: z.ZodObject<{
    ok: z.ZodLiteral<true>;
}, z.core.$strip>;
//# sourceMappingURL=api.d.ts.map