import { z } from 'zod';
/** Every stage of the governed commerce loop. */
export declare const RunStage: z.ZodEnum<{
    policy: "policy";
    intent: "intent";
    discover: "discover";
    evaluate: "evaluate";
    decide: "decide";
    prepare: "prepare";
    approve: "approve";
    pay: "pay";
    verify: "verify";
    automate: "automate";
    audit: "audit";
    done: "done";
}>;
export type RunStageT = z.infer<typeof RunStage>;
export declare const RunStatus: z.ZodEnum<{
    blocked: "blocked";
    failed: "failed";
    awaiting_approval: "awaiting_approval";
    cancelled: "cancelled";
    queued: "queued";
    running: "running";
    completed: "completed";
}>;
export type RunStatusT = z.infer<typeof RunStatus>;
export declare const ToolName: z.ZodEnum<{
    parse_intent: "parse_intent";
    validate_constraints: "validate_constraints";
    catalog_search: "catalog_search";
    product_details: "product_details";
    compare_products: "compare_products";
    evidence_lookup: "evidence_lookup";
    score_candidate: "score_candidate";
    explain_tradeoffs: "explain_tradeoffs";
    policy_check: "policy_check";
    create_paypal_order: "create_paypal_order";
    request_approval: "request_approval";
    capture_payment: "capture_payment";
    get_paypal_order: "get_paypal_order";
    verify_order: "verify_order";
    trigger_automation: "trigger_automation";
    search_events: "search_events";
}>;
export type ToolNameT = z.infer<typeof ToolName>;
export declare const ToolCallStatus: z.ZodEnum<{
    error: "error";
    denied: "denied";
    ok: "ok";
}>;
export declare const ToolCallRecord: z.ZodObject<{
    id: z.ZodString;
    runId: z.ZodString;
    correlationId: z.ZodString;
    tool: z.ZodEnum<{
        parse_intent: "parse_intent";
        validate_constraints: "validate_constraints";
        catalog_search: "catalog_search";
        product_details: "product_details";
        compare_products: "compare_products";
        evidence_lookup: "evidence_lookup";
        score_candidate: "score_candidate";
        explain_tradeoffs: "explain_tradeoffs";
        policy_check: "policy_check";
        create_paypal_order: "create_paypal_order";
        request_approval: "request_approval";
        capture_payment: "capture_payment";
        get_paypal_order: "get_paypal_order";
        verify_order: "verify_order";
        trigger_automation: "trigger_automation";
        search_events: "search_events";
    }>;
    arguments: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    status: z.ZodEnum<{
        error: "error";
        denied: "denied";
        ok: "ok";
    }>;
    startedAt: z.ZodString;
    durationMs: z.ZodNumber;
    resultSummary: z.ZodOptional<z.ZodString>;
    error: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export type ToolCallRecordT = z.infer<typeof ToolCallRecord>;
export declare const Run: z.ZodObject<{
    id: z.ZodString;
    intentId: z.ZodString;
    correlationId: z.ZodString;
    stage: z.ZodEnum<{
        policy: "policy";
        intent: "intent";
        discover: "discover";
        evaluate: "evaluate";
        decide: "decide";
        prepare: "prepare";
        approve: "approve";
        pay: "pay";
        verify: "verify";
        automate: "automate";
        audit: "audit";
        done: "done";
    }>;
    status: z.ZodEnum<{
        blocked: "blocked";
        failed: "failed";
        awaiting_approval: "awaiting_approval";
        cancelled: "cancelled";
        queued: "queued";
        running: "running";
        completed: "completed";
    }>;
    engine: z.ZodObject<{
        name: z.ZodEnum<{
            deterministic: "deterministic";
            "llm-assisted": "llm-assisted";
            llm: "llm";
        }>;
        provider: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        usedLlm: z.ZodBoolean;
        latencyMs: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
    progress: z.ZodNumber;
    progressLabel: z.ZodString;
    candidateCount: z.ZodNumber;
    shortlistedProductIds: z.ZodArray<z.ZodString>;
    planId: z.ZodNullable<z.ZodString>;
    policyId: z.ZodNullable<z.ZodString>;
    blockedReason: z.ZodNullable<z.ZodString>;
    summary: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export type RunT = z.infer<typeof Run>;
export declare const EventType: z.ZodEnum<{
    "run.created": "run.created";
    "run.stage.changed": "run.stage.changed";
    "run.failed": "run.failed";
    "run.cancelled": "run.cancelled";
    "intent.created": "intent.created";
    "intent.updated": "intent.updated";
    "catalog.search.started": "catalog.search.started";
    "catalog.search.completed": "catalog.search.completed";
    "product.retrieved": "product.retrieved";
    "product.evaluated": "product.evaluated";
    "shortlist.created": "shortlist.created";
    "evidence.gap.detected": "evidence.gap.detected";
    "policy.checked": "policy.checked";
    "policy.updated": "policy.updated";
    "plan.created": "plan.created";
    "plan.invalidated": "plan.invalidated";
    "approval.requested": "approval.requested";
    "approval.granted": "approval.granted";
    "approval.denied": "approval.denied";
    "approval.expired": "approval.expired";
    "paypal.order.created": "paypal.order.created";
    "paypal.approval.completed": "paypal.approval.completed";
    "payment.captured": "payment.captured";
    "payment.failed": "payment.failed";
    "order.verified": "order.verified";
    "automation.triggered": "automation.triggered";
    "automation.failed": "automation.failed";
    "action.failed": "action.failed";
    "tool.called": "tool.called";
    "system.health": "system.health";
}>;
export type EventTypeT = z.infer<typeof EventType>;
export declare const AuditEvent: z.ZodObject<{
    id: z.ZodString;
    correlationId: z.ZodString;
    runId: z.ZodNullable<z.ZodString>;
    type: z.ZodEnum<{
        "run.created": "run.created";
        "run.stage.changed": "run.stage.changed";
        "run.failed": "run.failed";
        "run.cancelled": "run.cancelled";
        "intent.created": "intent.created";
        "intent.updated": "intent.updated";
        "catalog.search.started": "catalog.search.started";
        "catalog.search.completed": "catalog.search.completed";
        "product.retrieved": "product.retrieved";
        "product.evaluated": "product.evaluated";
        "shortlist.created": "shortlist.created";
        "evidence.gap.detected": "evidence.gap.detected";
        "policy.checked": "policy.checked";
        "policy.updated": "policy.updated";
        "plan.created": "plan.created";
        "plan.invalidated": "plan.invalidated";
        "approval.requested": "approval.requested";
        "approval.granted": "approval.granted";
        "approval.denied": "approval.denied";
        "approval.expired": "approval.expired";
        "paypal.order.created": "paypal.order.created";
        "paypal.approval.completed": "paypal.approval.completed";
        "payment.captured": "payment.captured";
        "payment.failed": "payment.failed";
        "order.verified": "order.verified";
        "automation.triggered": "automation.triggered";
        "automation.failed": "automation.failed";
        "action.failed": "action.failed";
        "tool.called": "tool.called";
        "system.health": "system.health";
    }>;
    actor: z.ZodString;
    source: z.ZodString;
    payload: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    timestamp: z.ZodString;
    severity: z.ZodEnum<{
        error: "error";
        info: "info";
        warn: "warn";
    }>;
    sequence: z.ZodNumber;
}, z.core.$strip>;
export type AuditEventT = z.infer<typeof AuditEvent>;
export declare const AutomationRun: z.ZodObject<{
    id: z.ZodString;
    triggerEventId: z.ZodString;
    runId: z.ZodNullable<z.ZodString>;
    purchasePlanId: z.ZodNullable<z.ZodString>;
    zapierHook: z.ZodString;
    status: z.ZodEnum<{
        failed: "failed";
        sent: "sent";
        unconfigured: "unconfigured";
        pending_retry: "pending_retry";
    }>;
    responseSummary: z.ZodString;
    executedAt: z.ZodString;
    attempt: z.ZodNumber;
}, z.core.$strip>;
export type AutomationRunT = z.infer<typeof AutomationRun>;
export declare const CreateRunRequest: z.ZodObject<{
    intentId: z.ZodString;
    productIds: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export type CreateRunRequestT = z.infer<typeof CreateRunRequest>;
export declare const RunSnapshot: z.ZodObject<{
    run: z.ZodObject<{
        id: z.ZodString;
        intentId: z.ZodString;
        correlationId: z.ZodString;
        stage: z.ZodEnum<{
            policy: "policy";
            intent: "intent";
            discover: "discover";
            evaluate: "evaluate";
            decide: "decide";
            prepare: "prepare";
            approve: "approve";
            pay: "pay";
            verify: "verify";
            automate: "automate";
            audit: "audit";
            done: "done";
        }>;
        status: z.ZodEnum<{
            blocked: "blocked";
            failed: "failed";
            awaiting_approval: "awaiting_approval";
            cancelled: "cancelled";
            queued: "queued";
            running: "running";
            completed: "completed";
        }>;
        engine: z.ZodObject<{
            name: z.ZodEnum<{
                deterministic: "deterministic";
                "llm-assisted": "llm-assisted";
                llm: "llm";
            }>;
            provider: z.ZodOptional<z.ZodString>;
            model: z.ZodOptional<z.ZodString>;
            usedLlm: z.ZodBoolean;
            latencyMs: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        progress: z.ZodNumber;
        progressLabel: z.ZodString;
        candidateCount: z.ZodNumber;
        shortlistedProductIds: z.ZodArray<z.ZodString>;
        planId: z.ZodNullable<z.ZodString>;
        policyId: z.ZodNullable<z.ZodString>;
        blockedReason: z.ZodNullable<z.ZodString>;
        summary: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
    intent: z.ZodOptional<z.ZodUnknown>;
    products: z.ZodArray<z.ZodUnknown>;
    evaluations: z.ZodArray<z.ZodUnknown>;
    shortlist: z.ZodNullable<z.ZodUnknown>;
    plan: z.ZodNullable<z.ZodUnknown>;
    approval: z.ZodNullable<z.ZodUnknown>;
    payment: z.ZodNullable<z.ZodUnknown>;
    automations: z.ZodArray<z.ZodUnknown>;
    events: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        correlationId: z.ZodString;
        runId: z.ZodNullable<z.ZodString>;
        type: z.ZodEnum<{
            "run.created": "run.created";
            "run.stage.changed": "run.stage.changed";
            "run.failed": "run.failed";
            "run.cancelled": "run.cancelled";
            "intent.created": "intent.created";
            "intent.updated": "intent.updated";
            "catalog.search.started": "catalog.search.started";
            "catalog.search.completed": "catalog.search.completed";
            "product.retrieved": "product.retrieved";
            "product.evaluated": "product.evaluated";
            "shortlist.created": "shortlist.created";
            "evidence.gap.detected": "evidence.gap.detected";
            "policy.checked": "policy.checked";
            "policy.updated": "policy.updated";
            "plan.created": "plan.created";
            "plan.invalidated": "plan.invalidated";
            "approval.requested": "approval.requested";
            "approval.granted": "approval.granted";
            "approval.denied": "approval.denied";
            "approval.expired": "approval.expired";
            "paypal.order.created": "paypal.order.created";
            "paypal.approval.completed": "paypal.approval.completed";
            "payment.captured": "payment.captured";
            "payment.failed": "payment.failed";
            "order.verified": "order.verified";
            "automation.triggered": "automation.triggered";
            "automation.failed": "automation.failed";
            "action.failed": "action.failed";
            "tool.called": "tool.called";
            "system.health": "system.health";
        }>;
        actor: z.ZodString;
        source: z.ZodString;
        payload: z.ZodRecord<z.ZodString, z.ZodUnknown>;
        timestamp: z.ZodString;
        severity: z.ZodEnum<{
            error: "error";
            info: "info";
            warn: "warn";
        }>;
        sequence: z.ZodNumber;
    }, z.core.$strip>>;
    toolCalls: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        runId: z.ZodString;
        correlationId: z.ZodString;
        tool: z.ZodEnum<{
            parse_intent: "parse_intent";
            validate_constraints: "validate_constraints";
            catalog_search: "catalog_search";
            product_details: "product_details";
            compare_products: "compare_products";
            evidence_lookup: "evidence_lookup";
            score_candidate: "score_candidate";
            explain_tradeoffs: "explain_tradeoffs";
            policy_check: "policy_check";
            create_paypal_order: "create_paypal_order";
            request_approval: "request_approval";
            capture_payment: "capture_payment";
            get_paypal_order: "get_paypal_order";
            verify_order: "verify_order";
            trigger_automation: "trigger_automation";
            search_events: "search_events";
        }>;
        arguments: z.ZodRecord<z.ZodString, z.ZodUnknown>;
        status: z.ZodEnum<{
            error: "error";
            denied: "denied";
            ok: "ok";
        }>;
        startedAt: z.ZodString;
        durationMs: z.ZodNumber;
        resultSummary: z.ZodOptional<z.ZodString>;
        error: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type RunSnapshotT = z.infer<typeof RunSnapshot>;
//# sourceMappingURL=events.d.ts.map