import { z } from 'zod';
import { ApprovePurchaseRequest, ApprovePurchaseResponse, ApiError, AutomationTestResponse, CapturePurchaseRequest, CapturePurchaseResponse, CatalogSearchRequest, CatalogSearchResponse, CreateIntentRequest, CreateIntentResponse, CreateRunRequest, DiscoveryResponse, EventQuery, EventSearchResponse, HealthResponse, ListPoliciesResponse, ListRunsResponse, PolicyCheckRequest, PolicyCheckResponse, PreparePurchaseRequest, PreparePurchaseResponse, Product, RunDetailResponse, RunResponse, ToolCallRecord, UpdateIntentConstraintsRequest, UpsertPolicyRequest, } from '@autopilot/schemas';
/**
 * The API contract, declared once and used for three things: the OpenAPI
 * document served by the API, the generated Postman collection, and a
 * verification step that fails if a documented route is not implemented.
 */
export const OPERATIONS = [
    {
        operationId: 'createIntent',
        method: 'post',
        path: '/api/intents',
        tag: 'Intent',
        summary: 'Parse a natural-language commerce request into a structured intent.',
        description: 'Runs the deterministic interpreter, optionally enriched by an LLM for classification and soft preferences only. Budget, currency and approval fields always come from the deterministic parser.',
        successStatus: 201,
        request: { schema: CreateIntentRequest, required: true },
        response: CreateIntentResponse,
        failureModes: [
            { status: 400, code: 'INVALID_INPUT', description: 'The request body failed schema validation.' },
        ],
    },
    {
        operationId: 'updateIntent',
        method: 'patch',
        path: '/api/intents/{intentId}',
        tag: 'Intent',
        summary: 'Update structured constraints after a user edit.',
        description: 'Used by the comparison grid when a constraint is edited in place; the agent re-evaluates deterministically.',
        successStatus: 200,
        pathParams: [{ name: 'intentId', description: 'Intent identifier' }],
        request: { schema: UpdateIntentConstraintsRequest, required: true },
        response: CreateIntentResponse,
    },
    {
        operationId: 'createRun',
        method: 'post',
        path: '/api/runs',
        tag: 'Runs',
        summary: 'Start an agent execution run for an intent.',
        description: 'Executes discovery, evaluation, decision and policy, then stops at the approval gate or reports a policy block.',
        successStatus: 201,
        request: { schema: CreateRunRequest, required: true },
        response: RunResponse,
        failureModes: [
            { status: 409, code: 'NO_CANDIDATES', description: 'Discovery returned no candidates for the intent.' },
        ],
    },
    {
        operationId: 'getRun',
        method: 'get',
        path: '/api/runs/{runId}',
        tag: 'Runs',
        summary: 'Read the full state of a run.',
        description: 'Returns intent, candidates, evaluations, shortlist, plan, approval, payment, automations, events and tool calls.',
        successStatus: 200,
        pathParams: [{ name: 'runId', description: 'Run identifier' }],
        response: RunDetailResponse,
    },
    {
        operationId: 'listRuns',
        method: 'get',
        path: '/api/runs',
        tag: 'Runs',
        summary: 'List recent runs.',
        successStatus: 200,
        response: ListRunsResponse,
    },
    {
        operationId: 'getRunEvents',
        method: 'get',
        path: '/api/runs/{runId}/events',
        tag: 'Runs',
        summary: 'Read the audit events of one run.',
        successStatus: 200,
        pathParams: [{ name: 'runId', description: 'Run identifier' }],
        response: z.array(z.unknown()),
    },
    {
        operationId: 'streamRun',
        method: 'get',
        path: '/api/runs/{runId}/stream',
        tag: 'Runs',
        summary: 'Server-sent events stream of run progress.',
        description: 'Emits run and event frames so the UI stays live without polling.',
        successStatus: 200,
        pathParams: [{ name: 'runId', description: 'Run identifier' }],
        response: z.unknown(),
    },
    {
        operationId: 'getRunToolCalls',
        method: 'get',
        path: '/api/runs/{runId}/tool-calls',
        tag: 'Audit',
        summary: 'Read the typed tool calls of a run with latency and status.',
        successStatus: 200,
        pathParams: [{ name: 'runId', description: 'Run identifier' }],
        response: z.object({ toolCalls: z.array(ToolCallRecord) }),
    },
    {
        operationId: 'searchDiscovery',
        method: 'post',
        path: '/api/discovery/search',
        tag: 'Discovery',
        summary: 'Search the catalog provider directly.',
        description: 'Uses Channel3 when configured; otherwise returns bundled reference records and marks the result degraded.',
        successStatus: 200,
        request: { schema: CatalogSearchRequest, required: true },
        response: CatalogSearchResponse,
        failureModes: [
            {
                status: 502,
                code: 'PROVIDER_UNAVAILABLE',
                description: 'The configured provider failed and no documented substitute was available.',
            },
        ],
    },
    {
        operationId: 'getProduct',
        method: 'get',
        path: '/api/products/{productId}',
        tag: 'Discovery',
        summary: 'Read one normalised product with its evidence references.',
        successStatus: 200,
        pathParams: [{ name: 'productId', description: 'Product identifier' }],
        response: z.object({ product: Product, provider: z.string(), tookMs: z.number() }),
    },
    {
        operationId: 'evaluateCandidates',
        method: 'post',
        path: '/api/evaluations',
        tag: 'Evaluation',
        summary: 'Re-evaluate candidates against the current intent constraints.',
        description: 'Deterministic scoring: the same intent and products always produce the same scores and trade-offs.',
        successStatus: 200,
        request: {
            schema: z.object({
                intentId: z.string(),
                productIds: z.array(z.string()).optional(),
                runId: z.string().optional(),
            }),
            required: true,
        },
        response: DiscoveryResponse,
    },
    {
        operationId: 'checkPolicy',
        method: 'post',
        path: '/api/policies/check',
        tag: 'Policy',
        summary: 'Evaluate money policy deterministically.',
        description: 'Returns a machine-readable decision with one result per rule (pass, warn or block), the policy version used, and an input hash that approvals are bound to.',
        successStatus: 200,
        request: { schema: PolicyCheckRequest, required: true },
        response: PolicyCheckResponse,
    },
    {
        operationId: 'listPolicies',
        method: 'get',
        path: '/api/policies',
        tag: 'Policy',
        summary: 'List policy versions.',
        successStatus: 200,
        response: ListPoliciesResponse,
    },
    {
        operationId: 'upsertPolicy',
        method: 'post',
        path: '/api/policies',
        tag: 'Policy',
        summary: 'Create or update a policy, which bumps an immutable version.',
        successStatus: 200,
        request: { schema: UpsertPolicyRequest, required: true },
        response: z.object({ policy: z.unknown() }),
    },
    {
        operationId: 'preparePurchase',
        method: 'post',
        path: '/api/purchases/prepare',
        tag: 'Purchase',
        summary: 'Prepare a purchase plan and create the PayPal order.',
        description: 'Re-prices the selected product, re-runs policy, and creates the PayPal order only when policy allows it. Returns an approval request when policy requires approval.',
        successStatus: 200,
        request: { schema: PreparePurchaseRequest, required: true },
        response: PreparePurchaseResponse,
        headers: [
            {
                name: 'Idempotency-Key',
                description: 'Deduplicates repeated prepare calls.',
                required: false,
                example: 'prepare-plan-123',
            },
        ],
        failureModes: [
            {
                status: 409,
                code: 'POLICY_BLOCKED',
                description: 'A policy rule blocked execution; no PayPal order was created.',
            },
            {
                status: 409,
                code: 'PRICE_CHANGED',
                description: 'The provider price changed since evaluation; the plan must be re-prepared.',
            },
        ],
    },
    {
        operationId: 'getPurchase',
        method: 'get',
        path: '/api/purchases/{planId}',
        tag: 'Purchase',
        summary: 'Read a purchase plan with its policy decision and approval state.',
        successStatus: 200,
        pathParams: [{ name: 'planId', description: 'Purchase plan identifier' }],
        response: PreparePurchaseResponse,
    },
    {
        operationId: 'approvePurchase',
        method: 'post',
        path: '/api/purchases/{planId}/approve',
        tag: 'Purchase',
        summary: 'Record explicit human approval bound to a plan hash and amount.',
        description: 'The supplied planHash must match the current plan; otherwise approval is refused so a stale screen can never authorise a changed plan.',
        successStatus: 200,
        pathParams: [{ name: 'planId', description: 'Purchase plan identifier' }],
        request: { schema: ApprovePurchaseRequest, required: true },
        response: ApprovePurchaseResponse,
        headers: [
            {
                name: 'Idempotency-Key',
                description: 'Deduplicates repeated approval calls.',
                required: false,
                example: 'approve-plan-123',
            },
        ],
        failureModes: [
            { status: 409, code: 'PLAN_HASH_MISMATCH', description: 'The plan changed after the human reviewed it.' },
            { status: 409, code: 'APPROVAL_EXPIRED', description: 'The approval request expired and must be re-requested.' },
        ],
    },
    {
        operationId: 'capturePurchase',
        method: 'post',
        path: '/api/purchases/{planId}/capture',
        tag: 'Purchase',
        summary: 'Execute the payment and independently verify the resulting order state.',
        description: 'Requires a granted approval bound to the current plan hash. Captures are idempotent, so a second call never double-charges.',
        successStatus: 200,
        pathParams: [{ name: 'planId', description: 'Purchase plan identifier' }],
        request: { schema: CapturePurchaseRequest, required: true },
        response: CapturePurchaseResponse,
        headers: [
            {
                name: 'Idempotency-Key',
                description: 'Deduplicates repeated capture calls.',
                required: false,
                example: 'capture-plan-123',
            },
        ],
        failureModes: [
            { status: 409, code: 'APPROVAL_REQUIRED', description: 'No valid approval exists for this plan.' },
            {
                status: 402,
                code: 'PAYMENT_FAILED',
                description: 'The provider rejected the capture; no payment was verified.',
            },
        ],
    },
    {
        operationId: 'getPayment',
        method: 'get',
        path: '/api/payments/{paymentId}',
        tag: 'Purchase',
        summary: 'Verify payment and order state independently.',
        description: 'Re-reads the order from the payment provider and returns the observed state, never a client-side assumption.',
        successStatus: 200,
        pathParams: [{ name: 'paymentId', description: 'Payment identifier' }],
        response: z.object({
            payment: z.unknown(),
            observed: z.unknown(),
            verified: z.boolean(),
        }),
    },
    {
        operationId: 'testAutomation',
        method: 'post',
        path: '/api/automations/test',
        tag: 'Automation',
        summary: 'Send a test payload to the configured Zapier catch hook.',
        description: 'Never moves money. Reports unconfigured honestly when no hook is set.',
        successStatus: 200,
        request: {
            schema: z.object({ purchasePlanId: z.string().optional() }),
            required: false,
        },
        response: AutomationTestResponse,
    },
    {
        operationId: 'searchEvents',
        method: 'get',
        path: '/api/events',
        tag: 'Audit',
        summary: 'Search audit events, backed by Elastic when configured.',
        description: 'Free-text search, type and severity filters, and facets over decision events, tool calls, policy outcomes and payment lifecycle events.',
        successStatus: 200,
        query: EventQuery,
        response: EventSearchResponse,
    },
    {
        operationId: 'getEvent',
        method: 'get',
        path: '/api/events/{eventId}',
        tag: 'Audit',
        summary: 'Read one audit event with its payload.',
        successStatus: 200,
        pathParams: [{ name: 'eventId', description: 'Event identifier' }],
        response: z.object({ event: z.unknown() }),
    },
    {
        operationId: 'getHealth',
        method: 'get',
        path: '/api/health',
        tag: 'System',
        summary: 'Service and provider health.',
        description: 'Reports exactly which integrations are live, configured, simulated or unavailable. Never exposes secrets.',
        successStatus: 200,
        response: HealthResponse,
    },
    {
        operationId: 'getOpenApi',
        method: 'get',
        path: '/api/openapi.json',
        tag: 'System',
        summary: 'OpenAPI 3.1 document generated from the live schemas.',
        successStatus: 200,
        response: z.unknown(),
    },
];
export const TAGS = [
    'Intent',
    'Runs',
    'Discovery',
    'Evaluation',
    'Policy',
    'Purchase',
    'Automation',
    'Audit',
    'System',
];
export const ERROR_SCHEMA = ApiError;
export function operationIds() {
    return OPERATIONS.map((operation) => operation.operationId);
}
export function operationKey(method, path) {
    return `${method.toUpperCase()} ${path}`;
}
export function findOperation(method, path) {
    return OPERATIONS.find((operation) => operation.method === method.toLowerCase() && operation.path === path);
}
export function allFailureCodes() {
    return [...new Set(OPERATIONS.flatMap((operation) => (operation.failureModes ?? []).map((m) => m.code)))].sort();
}
//# sourceMappingURL=contract.js.map