import type { ProductT } from '@autopilot/schemas';

/**
 * Bundled catalog used when Channel3 credentials are not configured.
 *
 * These records are clearly-labelled reference data shipped with the
 * repository (provider `local-catalog`), not scraped or fabricated live
 * inventory: prices are static examples and availability is a static field.
 * Every product built from this source carries `evidence.kind = 'provider_field'`
 * with source `local-catalog`, so the audit trail states exactly where a value
 * came from. Set CHANNEL3_BASE_URL/CHANNEL3_API_KEY to replace this source.
 */
export interface LocalCatalogRecord {
  externalId: string;
  title: string;
  brand: string;
  category: ProductT['category'];
  price: number;
  currency: string;
  listPrice?: number;
  availability: ProductT['availability']['status'];
  attributes: Record<string, number | string | null>;
}

export const LOCAL_CATALOG: LocalCatalogRecord[] = [
  {
    externalId: 'ap-mbp16-m4-pro-64',
    title: 'Aurora Pro 16 (M4 Pro, 64GB, 1TB)',
    brand: 'Aurora',
    category: 'laptop',
    price: 1899,
    currency: 'USD',
    availability: 'in_stock',
    attributes: {
      ram_gb: 64,
      storage_gb: 1024,
      cpu_cores: 14,
      cpu_score: 24500,
      gpu_vram_gb: 20,
      gpu_score: 22000,
      display_in: 16.2,
      weight_kg: 2.14,
      battery_wh: 100,
      warranty_years: 3,
    },
  },
  {
    externalId: 'ap-vertex15-rtx-64',
    title: 'Vertex 15 Studio (RTX 5070 Ti, 64GB, 2TB)',
    brand: 'Vertex',
    category: 'laptop',
    price: 2299,
    currency: 'USD',
    availability: 'in_stock',
    attributes: {
      ram_gb: 64,
      storage_gb: 2048,
      cpu_cores: 20,
      cpu_score: 31200,
      gpu_vram_gb: 16,
      gpu_score: 31000,
      display_in: 15.6,
      weight_kg: 2.1,
      battery_wh: 86,
      warranty_years: 3,
    },
  },
  {
    externalId: 'ap-nova14-m3-32',
    title: 'Nova 14 (M3, 32GB, 512GB)',
    brand: 'Nova',
    category: 'laptop',
    price: 1399,
    currency: 'USD',
    availability: 'in_stock',
    attributes: {
      ram_gb: 32,
      storage_gb: 512,
      cpu_cores: 11,
      cpu_score: 19800,
      gpu_vram_gb: 10,
      gpu_score: 15000,
      display_in: 14.2,
      weight_kg: 1.51,
      battery_wh: 72,
      warranty_years: 2,
    },
  },
  {
    externalId: 'ap-nova16-m3-48',
    title: 'Nova 16 (M3 Max, 48GB, 1TB)',
    brand: 'Nova',
    category: 'laptop',
    price: 1799,
    currency: 'USD',
    availability: 'preorder',
    attributes: {
      ram_gb: 48,
      storage_gb: 1024,
      cpu_cores: 14,
      cpu_score: 26800,
      gpu_vram_gb: 18,
      gpu_score: 26000,
      display_in: 16,
      weight_kg: 2.02,
      battery_wh: 80,
      warranty_years: 2,
    },
  },
  {
    externalId: 'ap-lyra13-air-32',
    title: 'Lyra Air 13 (U7, 32GB, 1TB)',
    brand: 'Lyra',
    category: 'laptop',
    price: 1199,
    currency: 'USD',
    availability: 'in_stock',
    attributes: {
      ram_gb: 32,
      storage_gb: 1024,
      cpu_cores: 12,
      cpu_score: 18400,
      gpu_vram_gb: null,
      gpu_score: null,
      display_in: 13.6,
      weight_kg: 1.24,
      battery_wh: 75,
      warranty_years: 2,
    },
  },
  {
    externalId: 'ap-lyra15-pro-32',
    title: 'Lyra Pro 15 (i9 HX, 32GB, 1TB)',
    brand: 'Lyra',
    category: 'laptop',
    price: 1499,
    currency: 'USD',
    availability: 'in_stock',
    attributes: {
      ram_gb: 32,
      storage_gb: 1024,
      cpu_cores: 16,
      cpu_score: 22900,
      gpu_vram_gb: 8,
      gpu_score: 14000,
      display_in: 15.4,
      weight_kg: 1.98,
      battery_wh: 70,
      warranty_years: 3,
    },
  },
  {
    externalId: 'ap-atlas17-xw-128',
    title: 'Atlas 17X Workstation (128GB, 4TB, RTX 5080)',
    brand: 'Atlas',
    category: 'laptop',
    price: 3499,
    currency: 'USD',
    availability: 'in_stock',
    attributes: {
      ram_gb: 128,
      storage_gb: 4096,
      cpu_cores: 24,
      cpu_score: 39800,
      gpu_vram_gb: 16,
      gpu_score: 34000,
      display_in: 17.3,
      weight_kg: 3.1,
      battery_wh: 99,
      warranty_years: 3,
    },
  },
  {
    externalId: 'ap-lyra12-slate-16',
    title: 'Lyra 12 Slate (U5, 16GB, 256GB)',
    brand: 'Lyra',
    category: 'laptop',
    price: 649,
    currency: 'USD',
    availability: 'in_stock',
    attributes: {
      ram_gb: 16,
      storage_gb: 256,
      cpu_cores: 8,
      cpu_score: 11200,
      gpu_vram_gb: null,
      gpu_score: null,
      display_in: 12.4,
      weight_kg: 1.05,
      battery_wh: 58,
      warranty_years: 1,
    },
  },
  {
    externalId: 'ap-nova15-m2-24',
    title: 'Nova 15 (M2, 24GB, 512GB)',
    brand: 'Nova',
    category: 'laptop',
    price: 1099,
    currency: 'USD',
    availability: 'out_of_stock',
    attributes: {
      ram_gb: 24,
      storage_gb: 512,
      cpu_cores: 10,
      cpu_score: 16200,
      gpu_vram_gb: 10,
      gpu_score: 13500,
      display_in: 15.3,
      weight_kg: 1.64,
      battery_wh: 68,
      warranty_years: 2,
    },
  },
  {
    externalId: 'ap-vertex14-dev-64',
    title: 'Vertex 14 Dev (RTX 4060, 64GB, 1TB)',
    brand: 'Vertex',
    category: 'laptop',
    price: 1479,
    currency: 'USD',
    availability: 'in_stock',
    attributes: {
      ram_gb: 64,
      storage_gb: 1024,
      cpu_cores: 14,
      cpu_score: 23400,
      gpu_vram_gb: 8,
      gpu_score: 19000,
      display_in: 14.5,
      weight_kg: 1.79,
      battery_wh: 78,
      warranty_years: 3,
    },
  },
  {
    externalId: 'ap-atlas16-air-32',
    title: 'Atlas 16 Air (M3, 32GB, 1TB)',
    brand: 'Atlas',
    category: 'laptop',
    price: 1599,
    currency: 'USD',
    availability: 'in_stock',
    attributes: {
      ram_gb: 32,
      storage_gb: 1024,
      cpu_cores: 11,
      cpu_score: 20400,
      gpu_vram_gb: 10,
      gpu_score: 15200,
      display_in: 16,
      weight_kg: 1.72,
      battery_wh: 84,
      warranty_years: 2,
    },
  },
  {
    externalId: 'ap-nova14-m3-16',
    title: 'Nova 14 (M3, 16GB, 256GB)',
    brand: 'Nova',
    category: 'laptop',
    price: 999,
    currency: 'USD',
    availability: 'in_stock',
    attributes: {
      ram_gb: 16,
      storage_gb: 256,
      cpu_cores: 11,
      cpu_score: 19600,
      gpu_vram_gb: 10,
      gpu_score: 14800,
      display_in: 14.2,
      weight_kg: 1.5,
      battery_wh: 70,
      warranty_years: 2,
    },
  },
];